### ISSUE TITLE
I can't compile the  project x265

### ISSUE THREAD

**Issue by kinghelong** [ShiftMediaProject/x265#5]
## Context

1>  ..\source\common\x86\blockcopy8.asm
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\BuildCustomizations\nasm.targets(68,5): error MSB3721: 命令“"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\"nasm.exe -Xvc -f win64 -o "E:\vs2022-shiftedia\SOURCE\x265\SMP\obj\Debug_10b\x64\libx265bit\blockcopy8.obj" -I"E:\vs2022-shiftedia\SOURCE\x265\SMP\\..\source\common\x86/" -DSTACK_ALIGNMENT=16 -DHIGH_BIT_DEPTH=1 -DX265_DEPTH=10 -DBIT_DEPTH=10 -DX265_NS=x265_10bit -DWIN32=1 -DARCH_X86_64=1  "E:\vs2022-shiftedia\SOURCE\x265\source\common\x86\blockcopy8.asm"”已退出，返回代码为 1。 [E:\vs2022-shiftedia\SOURCE\x265\SMP\libx265bit.vcxproj]
1>  ..\source\common\x86\blockcopy8.asm
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\BuildCustomizations\nasm.targets(68,5): error MSB3721: 命令“"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\"nasm.exe -Xvc -f win64 -o "E:\vs2022-shiftedia\SOURCE\x265\SMP\obj\Debug_12b\x64\libx265bit\blockcopy8.obj" -I"E:\vs2022-shiftedia\SOURCE\x265\SMP\\..\source\common\x86/" -DSTACK_ALIGNMENT=16 -DHIGH_BIT_DEPTH=1 -DX265_DEPTH=12 -DBIT_DEPTH=12 -DX265_NS=x265_12bit -DWIN32=1 -DARCH_X86_64=1  "E:\vs2022-shiftedia\SOURCE\x265\source\common\x86\blockcopy8.asm"”已退出，返回代码为 1。 [E:\vs2022-shiftedia\SOURCE\x265\SMP\libx265bit.vcxproj]
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: 命令“if exist ..\source\x265_config.h (
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: del ..\source\x265_config.h
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: )
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: if exist "E:\vs2022-shiftedia\SOURCE\x265\SMP\..\..\..\msvc\"\include\x265.h (
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: del "E:\vs2022-shiftedia\SOURCE\x265\SMP\..\..\..\msvc\"\include\x265.h
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: )
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: if exist "E:\vs2022-shiftedia\SOURCE\x265\SMP\..\..\..\msvc\"\include\x265_config.h (
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: del "E:\vs2022-shiftedia\SOURCE\x265\SMP\..\..\..\msvc\"\include\x265_config.h
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: )
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: MSBuild libx265bit.vcxproj /property:Configuration="Debug_10b",Platform="x64",SolutionDir="E:\vs2022-shiftedia\SOURCE\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: MSBuild libx265bit.vcxproj /property:Configuration="Debug_12b",Platform="x64",SolutionDir="E:\vs2022-shiftedia\SOURCE\FFmpeg\SMP\\",SolutionFileName="ffmpeg_deps.sln" /verbosity:m /nologo 
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(149,5): error MSB3073: :VCEnd”已退出，代码为 1。

## Steps to Reproduce

1.  
2.  
3.  
4.  

## Your Environment

* Version Used: libx265 sdk ver 10.0.10240.0
* Operating System and Version: windows 11
* Compiler and Version(s): vs2022

**Comment by Sibras** [comment]
There seems to be an issue with your nasm install, make sure that this is properly installed as per the readme for VSNASM.

Also your VS $(Outdir) variable appears to have incorrect values in it. If you have changed any Visual Studio project parameters then this may cause errors if you have set them up incorrectly.

**Comment by ludeen007** [comment]
I have similar problem. I add libx265bit.vcproj to ffmpeg_deps.sln manually, and see the its project name having "VS2010" in VS project view. So I retarget it to v143 toolset. and then i can successfully build it.

**Comment by Sibras** [comment]
Fixes for v143 toolset have been added to repo.

**Comment by kinghelong** [comment]
> v143 工具集的修复已添加到 repo。

Thank you, now it can be compiled and passed
